### ISSUE TITLE
pytorch fails to load on new installation

### ISSUE THREAD

**Issue by darknicht66** [snowzach/doods2#127]
Newly installed "snowzach/doods2:amd64" container on docker-ce 28.3.1.
Fully default configuration with no mapping of volumes or config files.

```
services:
  # DOODS2: https://github.com/snowzach/doods2
  doods2:
    image: snowzach/doods2:amd64
    restart: 'unless-stopped'
    ports:
      - 8080:8080
    networks:
      - doods2
networks:
  doods2:
    name: doods2
```

Pytorch fails to load with the following log messages:
```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
2025-07-06 14:51:25,522 - doods.doods - INFO - Registered detector type:tflite name:default
2025-07-06 14:51:28,779 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
/usr/local/lib/python3.11/dist-packages/torch/hub.py:293: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
2025-07-06 14:51:31,860 - doods.doods - ERROR - Could not create detector pytorch/pytorch: cannot import name 'torch_load' from 'ultralytics.utils.patches' (/usr/local/lib/python3.11/dist-packages/ultralytics/utils/patches.py)
2025-07-06 14:51:31,923 - uvicorn.error - INFO - Started server process [1]
2025-07-06 14:51:31,924 - uvicorn.error - INFO - Waiting for application startup.
2025-07-06 14:51:31,924 - uvicorn.error - INFO - Application startup complete.
2025-07-06 14:51:31,924 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
```

Looking at "/usr/local/lib/python3.11/dist-packages/ultralytics/utils/patches.py" there does not appear to be a 'torch_load' defined anymore.

```
root@3cc26ce1e88b:/opt/doods# grep "def " /usr/local/lib/python3.11/dist-packages/ultralytics/utils/patches.py
def imread(filename: str, flags: int = cv2.IMREAD_COLOR):
def imwrite(filename: str, img: np.ndarray, params=None):
def imshow(winname: str, mat: np.ndarray):
def torch_save(*args, use_dill=True, **kwargs):
root@3cc26ce1e88b:/opt/doods# 
```

**Comment by yozh** [comment]
I have the same issue after upgrading home assistant to 2025.7.1 and I`m using the DOODS2 add-on, all worked fine before that, now I also get errors like below, had to switch to default for right now, but would like to cont using pytorch.

`/usr/local/lib/python3.11/dist-packages/torch/hub.py:294: UserWarning: You are about to download and run code from an untrusted repository. In a future release, this won't be allowed. To add the repository to your trusted list, change the command to {calling_fn}(..., trust_repo=False) and a command prompt will appear asking for an explicit confirmation of trust, or load(..., trust_repo=True), which will assume that the prompt is to be answered with 'yes'. You can also use load(..., trust_repo='check') which will only prompt for confirmation if the repo is not already trusted. This will eventually be the default behaviour
  warnings.warn(
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to /root/.cache/torch/hub/master.zip
2025-07-11 20:43:04,544 - doods.doods - ERROR - Could not create detector pytorch/pytorch: cannot import name 'torch_load' from 'ultralytics.utils.patches' (/usr/local/lib/python3.11/dist-packages/ultralytics/utils/patches.py)`

**Comment by snowzach** [comment]
Yeah, the upside of yolo dynamically loading stuff is it's always up to date. The downside is they seem to break stuff a lot. I'm absolutely buried with life lately. I will do my best to have a look soon if I can.

**Comment by thedanbob** [comment]
I think the ultralytics python package just needs to be updated. I was able to get pytorch working by replacing the doods docker image with the following:

```Dockerfile
FROM snowzach/doods2:amd64
RUN pip3 install ultralytics --upgrade
```

**Comment by thedanbob** [comment]
I'm actually using the HA addon too but I left out some of the details. Here's all of what I did:

1. Figure out the local name of the running doods image:
```bash
$ docker ps | grep doods
8c19880754d4   d5f40609/amd64-addon-doods2-amd64:1  "python3 main.py -c …"  2 hours ago  Up 2 hours  0.0.0.0:8088->8080/tcp, [::]:8088->8080/tcp  addon_d5f40609_doods2-amd64
```

2. Create a Dockerfile in an empty directory with the following contents:

```Dockerfile
FROM snowzach/doods2:amd64
RUN pip3 install ultralytics --upgrade
CMD ["-c", "/data/options.json", "api"]
```

3. Build a new image with the same name as in (1):
```bash
docker build -t d5f40609/amd64-addon-doods2-amd64:1 .
```

4. Restart the addon.

**Comment by yozh** [comment]
> I'm actually using the HA addon too but I left out some of the details. Here's all of what I did:
> 
> 1. Figure out the local name of the running doods image:
> 
> $ docker ps | grep doods
> 8c19880754d4   d5f40609/amd64-addon-doods2-amd64:1  "python3 main.py -c …"  2 hours ago  Up 2 hours  0.0.0.0:8088->8080/tcp, [::]:8088->8080/tcp  addon_d5f40609_doods2-amd64
>  2. Create a Dockerfile in an empty directory with the following contents:
> 
> # change to whatever variant you’re using
> FROM snowzach/doods2:amd64
> RUN pip3 install ultralytics --upgrade
> CMD ["-c", "/data/options.json", "api"]
>  3. Build a new image with the same name as in (1):
> 
> docker build -t d5f40609/amd64-addon-doods2-amd64:1 .
>  4. Restart the addon.

Need to try this. When you say empty directory, exactly where was it in HA? And thanks for figuring it out.

**Comment by yozh** [comment]
> I just put it in `addons` which is empty for me, but it doesn’t actually matter too much. Docker pulls all files in the directory into its context when it’s building so an empty directory speeds things up a bit.

Got it. Will try tomorrow. Thanks again.

**Comment by zbalsc** [comment]
Okay folks... I updated the image.. give that a shot...

**Comment by snowzach** [comment]
Okay folks... I updated the image.. give that a shot...

**Comment by darknicht66** [comment]
Tested on amd64 and amd64-gpu. Confirmed working. Thanks for the quick turnaround.

**Comment by yozh** [comment]
worked for me on amd64 on HA. Thank you !

**Comment by yozh** [comment]
Since this wasnt closed, I`m having the same issue again, I tried to build a new container, but it doesnt seem to work. Can we fix it again please ?

EDIT: I was able to rebuild with ultralytics upgrade and it is working now.
